config/routes.rb
App20130412::Application.routes.draw do
  resources :fake_twitters

  root :to => 'fake_twitters#index'

end

app/models/fake_twitter.rb
class FakeTwitter < ActiveRecord::Base
  attr_accessible :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fake_twitters_controller.rb
class FakeTwittersController < ApplicationController
  # GET /fake_twitters
  # GET /fake_twitters.json
  def index
    @fake_twitters = FakeTwitter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fake_twitters }
    end
  end

  # GET /fake_twitters/1
  # GET /fake_twitters/1.json
  def show
    @fake_twitter = FakeTwitter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fake_twitter }
    end
  end

  # GET /fake_twitters/new
  # GET /fake_twitters/new.json
  def new
    @fake_twitter = FakeTwitter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fake_twitter }
    end
  end

  # GET /fake_twitters/1/edit
  def edit
    @fake_twitter = FakeTwitter.find(params[:id])
  end

  # POST /fake_twitters
  # POST /fake_twitters.json
  def create
    @fake_twitter = FakeTwitter.new(params[:fake_twitter])

    respond_to do |format|
      if @fake_twitter.save
        format.html { redirect_to @fake_twitter, notice: 'Fake twitter was successfully created.' }
        format.json { render json: @fake_twitter, status: :created, location: @fake_twitter }
      else
        format.html { render action: "new" }
        format.json { render json: @fake_twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fake_twitters/1
  # PUT /fake_twitters/1.json
  def update
    @fake_twitter = FakeTwitter.find(params[:id])

    respond_to do |format|
      if @fake_twitter.update_attributes(params[:fake_twitter])
        format.html { redirect_to @fake_twitter, notice: 'Fake twitter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fake_twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fake_twitters/1
  # DELETE /fake_twitters/1.json
  def destroy
    @fake_twitter = FakeTwitter.find(params[:id])
    @fake_twitter.destroy

    respond_to do |format|
      format.html { redirect_to fake_twitters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fake_twitters_helper.rb
module FakeTwittersHelper
end

app/views/fake_twitters/_form.html.haml
= simple_form_for @fake_twitter, :html => { :class => 'form-horizontal' } do |f|
  = f.input :tweet
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), fake_twitters_path, :class => 'btn'

app/views/fake_twitters/edit.html.haml
- model_class = FakeTwitter
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/fake_twitters/index.html.haml
- model_class = FakeTwitter
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:tweet)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @fake_twitters.each do |fake_twitter|
      %tr
        %td= link_to fake_twitter.id, fake_twitter_path(fake_twitter)
        %td= fake_twitter.tweet
        %td=l fake_twitter.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_fake_twitter_path(fake_twitter), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), fake_twitter_path(fake_twitter), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_fake_twitter_path, :class => 'btn btn-primary'

app/views/fake_twitters/new.html.haml
- model_class = FakeTwitter
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/fake_twitters/show.html.haml
- model_class = FakeTwitter
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:tweet) + ':'
  %br
  = @fake_twitter.tweet

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), fake_twitters_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_fake_twitter_path(@fake_twitter), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), fake_twitter_path(@fake_twitter), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "App20130412"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") App20130412
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"